---
engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
   paths:
   - "lib/**.rb"
exclude_paths:
- spec/**/*
